# Generated by Django 6.0.1 on 2026-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='back_image_at_index',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
