# Generated by Django 6.0.1 on 2026-02-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_background_image_aat_index_page_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='template_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
