# Generated by Django 6.0.1 on 2026-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_siteprofile_template_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='booktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_of_guest', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='siteprofile',
            old_name='template_address',
            new_name='template_address_for_checkout',
        ),
    ]
