# Generated by Django 6.0.1 on 2026-02-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booktable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='number_of_guest',
            new_name='number_of_guests',
        ),
    ]
